### PR TITLE
feat: upgrade kubernetes-gateway-api to v0.8.0

### PR DESCRIPTION
**Pull request by hassnatahmad**

### CODE REVIEW

**Comment by davidkornel** [comment]
@hassnatahmad Hi,

Thank you for the PR. Is there any specific reason to upgrade the gateway API to v0.8.0? Obviously, it would be nice to have the latest API version, however, we haven't got the time to test out, if everything works as it should. Have you experienced this with your version?

@rg0now May we have your opinion about the gateway API upgrade?

**Comment by hassnatahmad** [comment]
@davidkornel Thank you for quick response.
Reason being, if you have or need kubernetes gateway api crd's then you are bound with this chart.
Ideally we should install them from official kubernetes sig.
As for as this version is concerned i did in my local kind setup and it is working

**Comment by rg0now** [comment]
The problem is that we need to upgrade the Go imports in the operator as well: currently we use `sigs.k8s.io/gateway-api` v0.7.1 and this should be bumped to v0.8.0 first. So I'd like to ask you guys to hold this PR back until we manage to do the upgrades there first, should be no more than a week or so.

Thanks for the PR though!

**Comment by davidkornel** [comment]
@hassnatahmad As the upgrades are done
I accept it, thanks for the PR

**Pull request merged**
