### PR TITLE
chore(CI): Add install and upgrade tests

### PR DESCRIPTION
**Pull request by levaitamas**
This PR implements 2 important features:
- introduces a new test action that combines linting and installing helm charts from source on a kind cluster;
- adds an automated upgrade test action that installs and upgrades stunner and stunner-gateway-operator from stable to dev channel on a "real" kind cluster.

TODO? Might be a wise move to integrate test.yaml with existing publish workflows. wdyt?

### CODE REVIEW

**Comment by levaitamas** [comment]
> I assume the tests will fail due to the missing `--udp-thread-num` in the l7mp/stunner":0.14.0 image.

well, well, what a surprise: https://github.com/l7mp/stunner-helm/actions/runs/4789864342/jobs/8518238317?pr=13#step:7:139

**Comment by levaitamas** [comment]
@davidkornel: Please review this PR. I made some updates to 1) run install test only when publishing (this will fix the false positives) and 2) enable linting for all commits. I set the stable->dev upgrade test to be manually dispatchable with `workflow_dispatch`.

**Comment by davidkornel** [comment]
In general looks good, thanks
One question:
What is exactly the point of the upgrade test workflow? I mean do we want to integrate it somehow with some workflows or ...? It's OK for me to have it, I'm just thinking about how could we make it more usable. Let's say we could use it to test if a prev stable release is upgradeable to a newer one. It could be useful to prevent upgrade errors while upgrading to the latest stable version, especially in production deployments.
Not sure how `helm upgrade` works in depth. Is there any possibility that it will/could fail in our use cases?  (Perhaps if the `stunnerd` CLI parameter list changes but the helm hasn't been updated.)

**Comment by levaitamas** [comment]
> Let's say we could use it to test if a prev stable release is upgradeable to a newer one. It could be useful to prevent upgrade errors while upgrading to the latest stable version, especially in production deployments.

Exactly this was the motivation for the upgrade test. The next release version before it gets tagged is the same as the lastest `dev` version, so this way we can pre-test an upgrade. I am not familiar with the current release workflow, that is why I left it as a "manual" action instead of calling it in `publish` actions.

> Not sure how helm upgrade works in depth. Is there any possibility that it will/could fail in our use cases? (Perhaps if the stunnerd CLI parameter list changes but the helm hasn't been updated.)

Yes, I guess these kinds of mismatch issues can be detected with this test. But also note that this is not a panacea since it covers a simple upgrade only.

**Comment by davidkornel** [comment]
> Exactly this was the motivation for the upgrade test. The next release version before it gets tagged is the same as the latest `dev` version, so this way we can pre-test an upgrade. I am not familiar with the current release workflow, that is why I left it as a "manual" action instead of calling it in `publish` action.

You're right, sorry. If we want to include it in the publish workflow we need to trigger it. My idea would be from here:
https://github.com/l7mp/stunner/blob/main/.github/workflows/publish.yml#L55
Or include/call it somewhere here:
https://github.com/l7mp/stunner-helm/blob/test-upgrade/.github/workflows/publish.yaml#L21

My only concern with integrating it in its current form is that there might be breaking changes between stable releases, thus we would just block the publish with it. Or since we don't have that many releases we can do it manually and include the results in the release doc that it's upgradable or not. If you got any idea let me know. 

IMHO it is ready to be merged, and we can think about the proper usage later. Until then just use it manually. Wdyt?

**Comment by levaitamas** [comment]
> My only concern with integrating it in its current form is that there might be breaking changes between stable releases, thus we would just block the publish with it. Or since we don't have that many releases we can do it manually and include the results in the release doc that it's upgradable or not. If you got any idea let me know.

Thank you, that was spot-on observation! My only concern with the full-manual version is that we might forget to trigger it. That's why I made some changes in 17947be to schedule it weekly.

**Pull request merged**
