### PR TITLE
Add podlabels to stunner-gateway-operator chart

### PR DESCRIPTION
**Pull request by bobertrublik**
This PR adds podlabels to the `stunner-auth` and `stunner-gateway-operator-controller-manager` deployments.

### CODE REVIEW

**Comment by levaitamas** [comment]
hi @bobertrublik,
Thanks for the PR! LGTM, but before merging I was wondering whether we should enable `podLabels` on the dataplane pods too. What is your use case for labeling only the auth-service and gateway-operator deployments but not the dataplane pods?

**Comment by bobertrublik** [comment]
In https://github.com/l7mp/stunner-gateway-operator/issues/45 it was decided that pod template labels are fixed and it's not intended to add additional labels. My use case is that I want to apply a semantic label system  that enrich metrics and logs emitted from a pod. Since both the logs and metrics have the same labels applied I can create unified dashboards and use the same label variables.

Would it be possible to reconsider that decision @rg0now? In the code comments you are saying this:

> // These labels are used for the Deployment selector. Note that deployment-level labels are NOT
// propagated to the pods to avoid unexpected conflicts.

From my point of view there shouldn't be any unforeseen conflicts at all. You have a fixed set of selector labels in the Deployment which are used to match a unique pod. Adding an arbitrary amount of labels to a pod won't affect the parent Deployment selector. 

I'd be very grateful if you would reconsider. :)

**Comment by rg0now** [comment]
The problem is the following: we use labels and annotations to manage specifics of how the Gateway is exposed. If any of these are propagated into the pods then every time you change a Gateway attribute your all affected `stunnerd` pods will restart (because changing pod labels/attributes induces a full pod restart in Kubernetes). Say, you set the health-check interval and bang, your whole gateway dataplane restarts, disconnecting all active connections. That's the reason behind this decision. Note sure I see any way to avoid this, and random pod restarts is something we really want to avoid.  

Now, you can use a K8s policy framework to add your labels to the pods, or you can disable STUNner's managed dataplane all together and provide your own `stunnerd` Deployment. See more info [here](https://github.com/l7mp/stunner-helm/pull/29#issuecomment-2162693533).

**Review by rg0now — CHANGES_REQUESTED** [review]

**Comment by rg0now** [comment]
Otherwise I'm fine with the change (except the above small tipo), but unfortunately this will still not add any labels to the `stunnerd` pods. Let know if you have a proposal for solving that without the pod restarts.

**Review by rg0now — APPROVED** [review]

**Pull request merged**
